name: Python application
on:
  push:
    branches: [ "**" ]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest tests
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and push Docker image
      if: github.event_name != 'pull_request'
      run: |
        docker buildx create --use
        docker buildx build \
          --file Dockerfile \
          --tag denct0506/news-api-python:latest \
          --platform linux/amd64,linux/arm64 \
          --push .
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: news-api-python
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
